name: CI

on:
  push:
  pull_request:

jobs:
  # Enforces the consistency of code formatting using `.eslintrc.json`
  check:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Prepare
        run: npm run prepare

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run all

  publish_release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name	}}
          tag: ${{ github.ref_name }}
